$ANSIBLE_VAULT;1.1;AES256
63643631343636633130666562346464613133613038303335353637633038303065633764636132
3465616238363564653237613932366363633233353365340a303034313930343730326638623462
37663964383133643432323234373162653734336139306333306336333438363633313162663962
3865646438643135620a336137313134393236313666656632353030353537343230363033346234
39653364333262613239666462653462643435626530633235663162336164353633656332326332
33623265646266623731393630653666663237303239653735646365326331653539363730653636
38366536333166316535636239333961366332643331396264346138313130316233666632366237
33383932313438393866333164326233306232396562363039336338383339346635643866633737
36616432633762373036663636363666346132383665303865316232373830363465643561316663
33303837623731373063346639393763623861373863656463636132616234313035313639656538
62396639313064323939646665656464363732376433356666613864303261386638313662346433
36326239323038356230643461646135306464386631653965663339353530323034376531393761
31646436333639666533666130613736333662363266666234303435383064313133653834633139
31313336316261356539316233653739633536323161303634333038343033633464333264386361
63636265646136383335396364626666343939386332323635376432633162326334346462643230
35333231376137363238343339326234343332316333346438386433396236383837653333306561
32383766363261303664376366663264396335373465633063306261346231633962613637326139
39376666363733656364316432623336646161323432653163386637636565646566396362323062
35383434306265663433363864623934346338316464316364643536663864643839636466633034
36653531333561663061383862373164393035396435613131666265346634626537616134313739
63646265633037386365333534653438393630623462343566333637636663343834353430656463
3736303931633731383432326635623031356431393632646239
