$ANSIBLE_VAULT;1.1;AES256
36373939333735623032303563363961356131366232393837383934346434376431613536343833
3930376638326135396237373139656462326130633333390a646564663135313937326361343338
33663630376562303139323632666262643933393633313030313438663039356234666563646264
3562613732663661330a343632653236626465653033386239613163323363623131383133333834
32323566633830636536353033396162333132366363343139316261333937373766303366353764
32646430623934396237376431623866333635363862323731336462663135656534626462316135
64343662306633386138366333336331353964643437333233646566353738313636326230356561
64393330663762653865373433383335626331613438346364366137633463336437306562353634
65646431616166333536353736393337646539313064363636396233613337643464373236383230
65366436613162366335346161623764633738646131373339333930626465316463386334366133
62333561656335356662373138613636653831373830313130656661366639623330366232363566
31623864663362653633623364663163356333656262313935666334333765323463396232336538
32306537363336646566636233646134373533643536653239316364316366613232323536313439
63646433613335653738656534306532303736373238363939343032303835383332623330386562
38323234393537633463366433356236393530396236306334386231346264313631393932366366
63316635326339643439333735373334386637666431633465363762313339376436333762343030
64303334386137346163623132373534616665333633303231393735346538316237663034306434
63366237643931316637363339353461393766346466306437636636306461386331353063303365
61643563303664376361623561303934363738303130393231333134636539326130613932326536
39303932633330353936396137373861356265373033623035666666356233323961623534396163
64653832336563316639653864313633623736363834323131646436643466363065653932313261
37666634383961323064626264306164303662663733623063653733393864663238613935613637
37313264646162633835386137376233343164623831653237333038313065326463306135383031
66326534653137663133
