all:
  children:
    prod_k8s:
      hosts:
        prod-k8s-master:
          ansible_host: 172.17.228.201
          ansible_user: ubuntu
          environment: prod
          deployment_type: k8s
          kubeconfig_path: "~/.kube/prod-config"
